config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  root 'pages#welcome'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#send_contact'
  get 'work', to: 'pages#work'
  get 'thanks', to: 'pages#thanks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def base_uri
        @base_uri ||= ENV["API_URI"]
    end
end

app/controllers/pages_controller.rb
require 'net/http'

class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_profile, only: [:welcome, :about]
  
  def welcome
  end

  def about
  end

  def work
    uri = URI("#{base_uri}/projects")
    res = Net::HTTP.get_response(uri)
    string_data = res.body if res.is_a?(Net::HTTPSuccess)
    projects = JSON.parse string_data
    @data = OpenStruct.new(projects: projects)
  end

  def contact

  end

  def send_contact
    name = "*Name*: `#{contact_params["name"]}`\n"
    email = "*Email*: `#{contact_params["email"]}`\n"
    message = "*Message*: `#{contact_params["message"]}`"

    bot_token = Rails.application.credentials.dig(:telegram, :bot_token)
    chat_id = Rails.application.credentials.dig(:telegram, :chat_id)
    
    uri = URI("https://api.telegram.org/bot#{bot_token}/sendMessage")
    
    req = Net::HTTP::Post.new(uri)
    req.body = {
      text: name << email << message,
      chat_id: chat_id,
      parse_mode: "MARKDOWN"
    }.to_json
    req.content_type = 'application/json'
    
    res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(req)
    end
    
    if res.code == '200'
      redirect_to :thanks
    end
  end

  def thanks

  end

  private

  def contact_params
    params.permit(:name, :email, :message)
  end

  def set_profile
    uri = URI("#{base_uri}/users/bekhruzRakhmonov")
    res = Net::HTTP.get_response(uri)
    string_data = res.body if res.is_a?(Net::HTTPSuccess)
    json_data =  JSON.parse string_data
    @image = json_data[0]["image"]
    @about = json_data[0]["about"]
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bekhruzbek's Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Blog", "https://bekhruzbek.onrender.com" %></li>
          <li><%= link_to "Work", work_path %></li>
        </ul>
      </nav>
      <h1>Bekhruzbek Rakhmonov</h1>
    </header>
    <main><%= yield %></main>
    <% if request.path != "/work"%>
      <footer>
        <ul class="social-icons">
          <li><%= link_to image_tag('github.png'), 'https://github.com/bekhruzRakhmonov' %></li>
          <li><%= link_to image_tag('linkedin.png'), 'https://linkedin.com/in/bekhruzbek-rakhmonov-903862225' %></li>
          <li><%= link_to image_tag('twitter.png'), 'https://twitter.com/BehruzRaxmonov' %></li>
        </ul>
        <p>&copy; <%= Time.now.year %> Bekhruzbek Rakhmonov. All rights reserved.</p>
      </footer>
    <% end %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<section class="about-section">
  <div class="about-content">
    <img src="<%= @image %>" alt='My Photo', class='profile-photo' >
    <h2>About Me</h2>
    <p>
      <%= @about %>
    </p>
  </div>
</section>

app/views/pages/contact.html.erb
<section class="contact-section">
  <div class="contact-content">
    <h2>Contact Me</h2>
    <p>If you'd like to get in touch, please fill out the form below.</p>

    <%= form_with(url: contact_path, method: :post) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= form.label :message %>
        <%= form.text_area :message, class: 'form-control', rows: 4, required: true %>
      </div>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</section>

app/views/pages/thanks.html.erb
<section class="container">
    <div class="jumbotron">
        <h1 class="display-4">Thank You!</h1>
        <p class="lead">Your message has been received. I'll get back to you soon.</p>
        <hr class="my-4">
        <p><a href="<%= root_path %>" class="btn btn-primary ">Go back to Home</a></p>
    </div>
</section>

app/views/pages/welcome.html.erb
<section class="tagline">
  <img src="<%= @image %>" alt='My Photo', class='profile-photo' >
  <p>Software Engineer</p>
  <%= link_to "View my Work", work_path, class: "btn btn-primary" %>
  <%= link_to "About me", about_path, class: "btn btn-outline-primary" %>
</section>

app/views/pages/work.html.erb
<section class="work-section">
  <% @data.projects.each do |project| %>
    <div class="card mb-3">
      <div id="carousel<%= project['id'] %>" class="carousel slide">
          <div class="carousel-inner">
            <% project["images"].each_with_index do |image, index| %>
              <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
                <img src="<%= image["url"] %>" class="d-block w-100 carousel-img" alt="project-img">
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= project['id'] %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= project['id'] %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      <div class="card-body">
        <a href="<%= project['link'] %>" class="card-title project-link"><%= project["title"] %></a>
        <p class="card-text"><%= project["description"] %></p>
      </div>
    </div>
  <% end %>
</section>